### ISSUE TITLE
Add more to .gitignore

### ISSUE THREAD

**Issue by kapunahelewong** [kapunahelewong/git-playground#2]
.gitignore is really small. Let's add some more.

**Comment by pedropnaves** [comment]
Added some default folders automatically generated by IDE's. #17

Anyway we can improve a little bit.

**Comment by pedropnaves** [comment]
Hello @kapunahelewong , this issue has been resolved in PR #17 
I think we can close them.

**Comment by kapunahelewong** [comment]
You're right, thank you, @pedropnaves!
