### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by kapunahelewong** [kapunahelewong/git-playground#6]
There are some typos around. Would love a PR for fixing them!

**Comment by mohammedasker** [comment]
Alright! I'm working to fix it. I believe you're referring to typos in pull-request.html file, right ?

**Comment by kapunahelewong** [comment]
They could be anywhere, really! I generally tend to leave them in so that people will have things to make PRs for, and I think I've seen some here and there, so it's wherever they are - like little surprises.  I can't remember exactly where they are though. Hm....maybe I should make a typo page - just full of typos. That'd be fun. You're giving me ideas, @mohammedasker!

**Comment by kapunahelewong** [comment]
Closing because @mohammedasker fixed it in #19. :)
